### ISSUE TITLE
undefined method `synchronize' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by sblond** [watir/watir-rspec#7]
Hi,
I was using v0.0.3, and then had issues after updating to v1.1.0.
When I create a new ActiveRecord instance in a spec, I get the following error:

```
NoMethodError:
       undefined method `synchronize' for nil:NilClass
```

After investigating a bit, I wonder if changes in file lib/watir/rspec/active_record_shared_connection.rb from commit c1ed8761bf5ca55060ab4259c0a769a705cbb211 could be responsible (@shared_connection_semaphore and @shared_connection are not visible in subclasses of ActiveRecord::Base).
